name    'Jimdo-check_debsums'
version '0.0.1'
source 'git://github.com/Jimdo/puppet-check_debsums'
author 'LarsFronius,Ole Michaelis'
dependency 'puppetlabs/stdlib', '3.0.0'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'
